# Generated by Django 2.2.4 on 2019-08-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceLoad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='iban',
        ),
        migrations.AddField(
            model_name='supplier',
            name='ibans',
            field=models.ManyToManyField(blank=True, null=True, to='InvoiceLoad.Bankaccount', verbose_name='Ibans du fournisseur'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='code',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='term',
            name='eom_1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='term',
            name='eom_2',
            field=models.IntegerField(),
        ),
    ]
