# Generated by Django 2.2.4 on 2019-08-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceLoad', '0002_auto_20190819_1731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'ordering': ['currency_from', 'date_valid_from']},
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('1', 'Reçue'), ('2', 'En cours de validation'), ('3', 'Renvoyée'), ('4', 'Approuvée')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='ibans',
            field=models.ManyToManyField(blank=True, to='InvoiceLoad.Bankaccount', verbose_name='Ibans du fournisseur'),
        ),
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together={('currency_from', 'currency_to', 'date_valid_from')},
        ),
        migrations.RemoveField(
            model_name='exchangerate',
            name='code',
        ),
    ]
