# Generated by Django 2.2.4 on 2019-08-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceLoad', '0003_auto_20190823_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('1', 'Reçue'), ('2', 'En cours de validation'), ('3', 'Renvoyée'), ('4', 'Approuvée'), ('5', 'Transmise'), ('90', 'Payée'), ('99', 'Supprimée')], default='1', max_length=2),
        ),
    ]
