# Generated by Django 2.2.4 on 2019-08-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceLoad', '0004_auto_20190823_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='image',
            field=models.FileField(upload_to='uploads/invoice/image/'),
        ),
    ]
