# Generated by Django 2.2.4 on 2019-09-02 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceLoad', '0006_auto_20190830_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='author',
        ),
    ]
